spring:
  application:
    name: backend
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123

server:
  port: 8080

logging:
  level:
    org.springframework.data.neo4j: INFO
